# Generated by Django 2.2.6 on 2019-11-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geoname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.Geoname')),
                ('responsible_for_places', models.ManyToManyField(blank=True, related_name='responsible_institutions', to='crud.Geoname')),
            ],
        ),
        migrations.CreateModel(
            name='CooperationalRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_relationships', to='crud.Geoname')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperational_relationships', to='crud.Institution')),
            ],
        ),
    ]
